### ISSUE TITLE
OSError: [WinError 127]Error loading "D:\TODO\Python37_9\lib\site-packages\torch\lib\cublas64_11.dll" or one of its dependencies.

### ISSUE THREAD

**Issue by 943fansi** [SeldonIO/alibi-detect#425] opened 2022-01-14 07:37 UTC
`from alibi_detect.datasets import fetch_kdd`
I can use tensorflow and pytorch normally, and `cublas64_11.dll` exists.
```
>>>print(tf.__version__)
2.4.1
>>> print(torch.__version__)
1.9.0+cu111
>>> print(alibi_detect.__version__)
0.8.0
```
The complete information of error reporting is as follows
```
line 1, in <module>
    from alibi_detect.datasets import fetch_kdd
  File "D:\TODO\Python37_9\lib\site-packages\alibi_detect\__init__.py", line 1, in <module>
    from . import ad, cd, models, od, utils
  File "D:\TODO\Python37_9\lib\site-packages\alibi_detect\ad\__init__.py", line 1, in <module>
    from .adversarialae import AdversarialAE
  File "D:\TODO\Python37_9\lib\site-packages\alibi_detect\ad\adversarialae.py", line 8, in <module>
    from alibi_detect.models.tensorflow.autoencoder import AE
  File "D:\TODO\Python37_9\lib\site-packages\alibi_detect\models\tensorflow\__init__.py", line 2, in <module>
    from .embedding import TransformerEmbedding
  File "D:\TODO\Python37_9\lib\site-packages\alibi_detect\models\tensorflow\embedding.py", line 3, in <module>
    from transformers import TFAutoModel, AutoConfig
  File "D:\TODO\Python37_9\lib\site-packages\transformers\__init__.py", line 43, in <module>
    from . import dependency_versions_check
  File "D:\TODO\Python37_9\lib\site-packages\transformers\dependency_versions_check.py", line 36, in <module>
    from .file_utils import is_tokenizers_available
  File "D:\TODO\Python37_9\lib\site-packages\transformers\file_utils.py", line 52, in <module>
    from huggingface_hub import HfFolder, Repository, create_repo, list_repo_files, whoami
  File "D:\TODO\Python37_9\lib\site-packages\huggingface_hub\__init__.py", line 59, in <module>
    from .hub_mixin import ModelHubMixin, PyTorchModelHubMixin
  File "D:\TODO\Python37_9\lib\site-packages\huggingface_hub\hub_mixin.py", line 16, in <module>
    import torch
  File "D:\TODO\Python37_9\lib\site-packages\torch\__init__.py", line 124, in <module>
    raise err
```
Very strangely, info about tf appears twice
```
2022-01-14 15:35:06.884649: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2022-01-14 15:35:10.097446: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-01-14 15:35:10.098949: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2022-01-14 15:35:10.141661: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 2060 computeCapability: 7.5
coreClock: 1.2GHz coreCount: 30 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 245.91GiB/s
2022-01-14 15:35:10.142772: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2022-01-14 15:35:10.161065: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2022-01-14 15:35:10.161345: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2022-01-14 15:35:10.177333: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2022-01-14 15:35:10.182175: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2022-01-14 15:35:10.193852: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2022-01-14 15:35:10.202690: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2022-01-14 15:35:10.204346: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2022-01-14 15:35:10.204689: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2022-01-14 15:35:10.205211: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-01-14 15:35:10.206735: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 2060 computeCapability: 7.5
coreClock: 1.2GHz coreCount: 30 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 245.91GiB/s
2022-01-14 15:35:10.207406: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2022-01-14 15:35:10.207746: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2022-01-14 15:35:10.208085: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2022-01-14 15:35:10.208425: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2022-01-14 15:35:10.208766: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2022-01-14 15:35:10.209095: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2022-01-14 15:35:10.209408: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2022-01-14 15:35:10.209695: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2022-01-14 15:35:10.210058: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2022-01-14 15:35:11.154813: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-01-14 15:35:11.155087: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 
2022-01-14 15:35:11.155249: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N 
2022-01-14 15:35:11.155625: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4720 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2060, pci bus id: 0000:01:00.0, compute capability: 7.5)
2022-01-14 15:35:11.157391: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
Traceback (most recent call last):
  File "C:/Users/lenovo/Desktop/DO/cs.py", line 1, in <module>
    from alibi_detect.datasets import fetch_kdd
```

**Comment by ascillitoe** [comment] 2022-01-14 09:25
Hi there, regarding the first error, I'm surprised PyTorch is working normally for you as the error suggests something is not good with your CUDA install. I'm wondering if it might be an issue with PyTorch interacting with the transformers library. A few bits of info would be helpful I think:

1. Can you post the output of `pip freeze` please (or `conda list --export` if using conda). 
2. How was PyTorch installed?
3. Does `torch.cuda.is_available()` return `True`?

Regarding the second traceback, did this raise any errors? I can't actually see any error or warning in the second?

**Comment by ascillitoe** [comment] 2022-01-14 09:39
Thanks! Can I also just check please, what command did you use to install PyTorch? Just so I can try to reproduce...

**Comment by 943fansi** [comment] 2022-01-14 09:44
Sorry, I forgot it, maybe use `pip in stall torch`. Now I am trying to install alibi-detect in a new virtual environment. Could you give me suggestions? Do I need to install  some dependencies in advance?

**Comment by ascillitoe** [comment] 2022-01-14 09:45
Also, one more thing, If you try the below import by itself does it work?

```python
from transformers import AutoConfig, AutoModel
```

I'd be interested in whether this works on your machine when `alibi_detect` is installed, and whether it works in a fresh virtualenv without `alibi_detect` installed.

**Comment by 943fansi** [comment] 2022-01-14 09:52
`finished with exit code 0`
```
from transformers import AutoConfig, AutoModel
from alibi_detect.datasets import fetch_kdd
```
same error
```
from alibi_detect.datasets import fetch_kdd
from transformers import AutoConfig, AutoModel
```

**Comment by ascillitoe** [comment] 2022-01-14 09:58
> Sorry, I forgot it, maybe use `pip install torch`. Now I am trying to install alibi-detect in a new virtual environment. Could you give me suggestions? Do I need to install some dependencies in advance?

My query above is somewhat related to this. Running `pip install alibi_detect` is usually sufficient, however this does assume you have a working PyTorch installation (or if you only want to use TensorFlow, it's better if you don't have PyTorch installed at all). Some of the detectors also rely on other packages such as [transformers](https://github.com/huggingface/transformers), so we also need these to be working correctly with Tensorflow/PyTorch. This usually just works, but as with anything CUDA related, sometimes installs can get a bit more challenging! 

The first thing I would recommend is to try to install PyTorch following [these instructions](https://pytorch.org/), i.e. for installation with pip:

```
pip3 install torch==1.10.1+cu113 torchvision==0.11.2+cu113 torchaudio===0.10.1+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
```

Although where pytorch is involved I often find it easier to use conda, as this will install a completely isolated `cudatoolkit` for you:

```
conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
```

Once Tensorflow and PyTorch are installed, I'd try to install `transformers` (since this is what appears to be causing problems) with `pip install transformers`, and then run the following two lines:

```python
from transformers import AutoTokenizer, AutoModel  # to test PyTorch
from transformers import TFAutoModel  # to test TensorFlow
```

I'd try this in a fresh virtualenv, and if all is good, then try installing `alibi_detect` again with `pip install alibi_detect`.

**Comment by ascillitoe** [comment] 2022-01-14 10:02
@943fansi as an aside, we are working on modularising `alibi_detect` so that you only have to install certain packages (such as tensorflow, transformers etc) if you actually want to use a detector that needs them, so this should become easier in the future. But for now, essentially you always have to install tensorflow, but pytorch is optional. Does your use case require pytorch specifically? Or could you make do with tensorflow for now?

**Comment by 943fansi** [comment] 2022-01-14 10:15
I'm a beginner. I can use tensorflow and pytorch. I'm looking for some time series libraries. I came from [`Merlion`](https://github.com/salesforce/Merlion) because it doesn't support `windows`. There are also problems with [Kats's](https://github.com/facebookresearch/Kats/issues/162) installation on `windows`. I want to reduce the time for building models, but it doesn't seem to be going well. :(

**Comment by 943fansi** [comment] 2022-01-14 10:32
@ascillitoe 
Can I just install `Pytorch` or `Tensorflow` to use `alibi_detect`? I have install `torch` by use `conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch`


```
pip install alibi_detect
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting alibi_detect
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/58/ce/abf4106e02acd50581b0de45f52c276e562f875e650c1592c0a4631f050d/alibi_detect-0.8.0-py3-none-any.whl (300 kB)
Collecting dill<0.4.0,>=0.3.0
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/b6/c3/973676ceb86b60835bb3978c6db67a5dc06be6cfdbd14ef0f5a13e3fc9fd/dill-0.3.4-py2.py3-none-any.whl (86 kB)
Collecting tensorflow!=2.6.0,!=2.6.1,<2.7.0,>=2.2.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/d1/fa/0f27349aae87a6c05f0e4b366f7cda3f3f082c916f12d57edbb73bb2afc1/tensorflow-2.6.2-cp37-cp37m-win_amd64.whl (423.3 MB)
     |█                               | 11.7 MB 1.3 MB/s eta 0:05:14
```

**Comment by ascillitoe** [comment] 2022-01-14 11:13
You should be able to use `alibi_detect` without `PyTorch` installed at all, with the caveat that you will only be able to use detectors with `backend='tensorflow'`. If you don't need PyTorch specifically I would recommend not installing it, as that will confuse matters.

**Comment by 943fansi** [comment] 2022-01-14 11:19
@ascillitoe Thanks. In the new virtual environment, both `PyToch` and `Tensorflow` are included and work normally.

**Comment by 943fansi** [comment] 2022-01-14 12:18
> Does `alibi_detect` also work in this new enviroment?

Yes, `alibi_detect` works well.

**Comment by ascillitoe** [comment] 2022-01-14 12:21
> > Does `alibi_detect` also work in this new enviroment?
> 
> Yes, `alibi_detect` works well.

Yay! I'll close this issue for now then, but please do feel free to reopen (or create another) if you encounter further issues 🙂

**Closed by ascillitoe** 2022-01-14 12:21 UTC
