### ISSUE TITLE
[Question] [SR] How to disable lower bound anomalies

### ISSUE THREAD

**Issue by tnpradeep** [SeldonIO/alibi-detect#533] opened 2022-06-09 05:36 UTC
Hi Experts,

I was trying to use SR for detecting anomalies in time series data set.
And observed that SR is detecting both upper bound ( meaning data points above the threshold) and lower bound (data points below threshold, may be contextual to previous data points).

So, what I am looking for is to detect only the anomalies which goes above the threshold and not interested in the points which drops below the lower threshold.

Below is my parameters for SR,

```
od = SpectralResidual(
    threshold=1.,
    window_amp=15,
    window_local=15,
    padding_amp_method='replicate',
    padding_local_method='replicate',
    padding_amp_side='left',
    n_est_points=15,
    n_grad_points=5
)
```
Reference plot:
![image](https://user-images.githubusercontent.com/13568762/172824991-cb35b422-f6a7-455f-98e5-9d369e4f2893.png)

Please guide me how I can achieve only upper threshold anomalies.

Thanks in advance
Pradeep

**Comment by RobertSamoilescu** [comment] 2022-06-10 11:00
Hi @tnpradeep.
Before answering your question, I need some more clarifications. Thus I will make a few remarks and ask some questions.

First, I would like to know if the figure you provided displays the signal per timestep and not the outlier scores per timestep?
Note that a data point is marked as an outlier if its outlier score exceeds the given threshold. Thus, if the plot you provided displays the signal vs time, then it is not very informative to understand the reason why the algorithm marked it as an outlier. You need to plot the outlier score per timestep along with a horizontal line corresponding to the threshold and see that some scores exceed the predefined threshold.

This is nicely illustrated in the `sr` example in alibi-detect (link [here](https://github.com/SeldonIO/alibi-detect/blob/master/doc/source/examples/od_sr_synth.ipynb)). 

![Screenshot from 2022-06-10 11-33-51](https://user-images.githubusercontent.com/22344480/173047573-340b0a22-42e3-4b49-8594-8899b303cb0d.png)

In this example, we created a synthetic dataset and we added some noise on top of it. The orange signal in the left figure is the ground truth signal, while the blue one is the noised version. As you can observe, there are some spikes that go above and below the signal for 5 timesteps. Those are the outliers that we are looking to detect. On the right hand side, we plotted the outlier scores (green bars) and the threshold (horizontal red line). As you can see, based on the threshold we provided, we were able to identify correctly the 5 outliers, because their outlier scores exceed the given threshold.

What I am trying to emphasize with this example is that the threshold is representative for the outlier scores and not for the actual signal. 

If the figure you provided displays the signal per timestep, then it is perfectly fine that some lower values are detected as outliers as they might be lower than what would be expected. Note that in the alibi-detect example, datapoints that have lower values (i.e. the one that goes below the ground-truth signal) are detected as outliers. On the other hand, if you look at the outlier score, you can see that the scores for those low value datapoints are actually high, which is the reason why we marked them as outliers.

Please let me know if those remarks helped. 
Also, I really recommend you to follow the alibi-detect example (link [here](https://github.com/SeldonIO/alibi-detect/blob/master/doc/source/examples/od_sr_synth.ipynb)) as it shows other features that you might be interested in (e.g. infer an appropriate threshold, zoom in to specific windows of your data for better visualizations, etc.)

If my comments did not help, it would be great if you can provide a bit more details on what is the problem you are trying to solve and what is the reason you are looking for some points and not others. If you can share the code and some data (if possible) that will also help us reproduce your setup and find possible solutions to your problem.

Thanks!

**Comment by ascillitoe** [comment] 2022-08-02 14:39
@tnpradeep I am closing this issue due to inactivity. Please feel free to reopen if you are still having issues!

**Closed by ascillitoe** 2022-08-02 14:39 UTC
Labels: Type: Question
