### ISSUE TITLE
Array type conversion error is occurred in cd_text_imdb example.

### ISSUE THREAD

**Issue by KevinRyu** [SeldonIO/alibi-detect#437] opened 2022-01-21 07:17 UTC
Hi,

In cd_text_imdb.ipynb example, below error is occurred. Input data x is ndarray of string type elements . By the way, torch. from_numpy(x) function deosn't support convert string array to tensor. Which code can do I fix?

Error message:

~\Miniconda3\envs\alibidet\lib\site-packages\alibi_detect\utils\pytorch\prediction.py in predict_batch(x, model, device, batch_size, preprocess_fn, dtype)
     37         device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
     38     if isinstance(x, np.ndarray):
---> 39        x = torch.from_numpy(x)
        40  n = len(x)

TypeError: can't convert np.ndarray of type numpy.str_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

Code block:

from alibi_detect.cd.pytorch import preprocess_drift
from alibi_detect.models.pytorch import TransformerEmbedding

embedding_pt = TransformerEmbedding(model_name, emb_type, layers)

model = nn.Sequential(
    embedding_pt,
    nn.Linear(768, 256),
    nn.ReLU(),
    nn.Linear(256, enc_dim)
).to(device).eval()

// define preprocessing function
preprocess_fn = partial(preprocess_drift, model=model, tokenizer=tokenizer, 
                        max_len=max_len, batch_size=32)

// initialise drift detector
cd = MMDDrift(X_ref, backend='pytorch', p_val=.05, preprocess_fn=preprocess_fn, 
              n_permutations=100, input_shape=(max_len,))

**Comment by ascillitoe** [comment] 2022-01-24 11:32
Hi @KevinRyu, thanks for flagging this one, you're on quite a roll with helping us find these issues! 🙂 

I've been able to reproduce this (on a GPU), as a quick fix, if you convert the numpy arrays to lists everything should work. For example:

```
cd = MMDDrift(list(X_ref), backend='pytorch', p_val=.05, preprocess_fn=preprocess_fn, 
              n_permutations=100, input_shape=(max_len,))

preds_h0 = cd.predict(list(X_h0))
```
etc...

This is not ideal behavior though, and I shall try to track down the cause of this regression.

**Comment by KevinRyu** [comment] 2022-01-25 12:00
Hi.

Thanks for your reply. I am gonna modify this example code even though your
guide is not ideal behavior.
Have a good day!



2022년 1월 24일 (월) 오후 8:33, Ashley Scillitoe ***@***.***>님이 작성:

**Comment by ascillitoe** [comment] 2022-01-25 14:11
Hi @KevinRyu, fyi the revised notebook is now in #438, and will hopefully be merged soon.

Note that `X_ref`, `X_h0` etc are now lists of strings (`List[str]`) instead of ndarray's. This is the format we recommend for use with text data, and is also used in NLP libraries such as `transformers` (see examples [here](https://huggingface.co/docs/transformers/preprocessing)). It just happens that our TensorFlow detectors work with both lists and ndarray's, but for consistency its best to use lists since these work with both our TensorFlow and PyTorch backends. 

One exception to this is in the final "Train embeddings from scratch" example. Here, the `uae` model expects a ndarray, so we have to define a `preprocess_batch_fn` in `preprocess_fn` in order to convert from list to ndarray before passing to the model.

**Closed** 2022-01-25 14:36 UTC
